apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "helm-chart.fullname" . }}
    labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard
